# Generated by Django 4.1.1 on 2022-10-02 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petsis_app', '0002_user_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='theme',
        ),
    ]
